/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ShowtimeDAO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Movie;
import model.ScreenRoom;
import model.Showtime;

/**
 *
 * @author danieldoisme
 */
public class SelectShowtimeFrm extends javax.swing.JFrame {

    private Movie selectedMovie;
    private ArrayList<Showtime> showtimes;

    /**
     * Creates new form SelectShowtimeFrm
     */
    private SelectShowtimeFrm() {
        initComponents();
    }

    public SelectShowtimeFrm(Movie movie) {
        initComponents();
        lblSelectedTitle.setText("Suất chiếu cho phim: " + movie.getTitle());

        ShowtimeDAO showtimeDAO = new ShowtimeDAO();
        this.showtimes = showtimeDAO.searchShowtimesByMovie(movie.getId());

        populateTable();
    }

    public SelectShowtimeFrm(ScreenRoom screenRoom) {
        initComponents();
        lblSelectedTitle.setText("Suất chiếu tại phòng: " + screenRoom.getRoomCode());

        ShowtimeDAO showtimeDAO = new ShowtimeDAO();
        this.showtimes = showtimeDAO.searchShowtimesByScreenRoom(screenRoom.getId());

        populateTable();
    }

    private void populateTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Suất chiếu");
        model.addColumn("Phim");
        model.addColumn("Giờ chiếu");
        model.addColumn("Giá vé");

        for (Showtime st : this.showtimes) {
            model.addRow(new Object[]{
                st.getId(),
                st.getMovie().getTitle(), // Hiển thị tên phim
                st.getShowTime(),
                st.getTicketPrice()
            });
        }
        tblShowtimes.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSelectedTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShowtimes = new javax.swing.JTable();
        btnSelectThisShowtime = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSelectedTitle.setText("Select Showtime");

        tblShowtimes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblShowtimes);

        btnSelectThisShowtime.setText("Chọn suất chiếu này");
        btnSelectThisShowtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectThisShowtimeActionPerformed(evt);
            }
        });

        btnBack.setText("Quay lại");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelectThisShowtime)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSelectedTitle)
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelectedTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelectThisShowtime)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectThisShowtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectThisShowtimeActionPerformed
        int selectedRow = tblShowtimes.getSelectedRow();
        if (selectedRow != -1) {
            Showtime selectedShowtime = this.showtimes.get(selectedRow);
            new SelectSeatFrm(selectedShowtime).setVisible(true);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn một suất chiếu!");
        }
    }//GEN-LAST:event_btnSelectThisShowtimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectShowtimeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectShowtimeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectShowtimeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectShowtimeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectShowtimeFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSelectThisShowtime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSelectedTitle;
    private javax.swing.JTable tblShowtimes;
    // End of variables declaration//GEN-END:variables
}
