/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.MovieDAO;
import dao.ScreenRoomDAO;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import model.Movie;
import model.ScreenRoom;

/**
 *
 * @author danieldoisme
 */
public class SellTicketFrm extends javax.swing.JFrame {

    private ArrayList<Movie> movies;
    private ArrayList<ScreenRoom> screenRooms;
    private String currentList = "movies";

    /**
     * Creates new form SellTicketFrm
     */
    public SellTicketFrm() {
        initComponents();
        // Mặc định hiển thị danh sách phim khi khởi tạo
        listMoviesBtnActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listMoviesBtn = new javax.swing.JButton();
        listScreenRoomsBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayList = new javax.swing.JList<>();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listMoviesBtn.setText("List Movies");
        listMoviesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listMoviesBtnActionPerformed(evt);
            }
        });

        listScreenRoomsBtn.setText("List Screen Rooms");
        listMoviesBtn = new javax.swing.JButton();
        listScreenRoomsBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayList = new javax.swing.JList<>();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listMoviesBtn.setText("List Movies");
        listMoviesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listMoviesBtnActionPerformed(evt);
            }
        });

        listScreenRoomsBtn.setText("List Screen Rooms");
        listScreenRoomsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listScreenRoomsBtnActionPerformed(evt);
            }
        });

        displayList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        displayList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                displayListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(displayList);

        lblTitle.setText("Movies");
        listScreenRoomsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listScreenRoomsBtnActionPerformed(evt);
            }
        });

        displayList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        displayList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                displayListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(displayList);

        lblTitle.setText("Movies");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(178, 178, 178))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listMoviesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(listScreenRoomsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listScreenRoomsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(listMoviesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitle)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_displayListValueChanged
        if (!evt.getValueIsAdjusting()) {
            int selectedIndex = displayList.getSelectedIndex();
            if (selectedIndex != -1) {
                if (currentList.equals("movies")) {
                    Movie selectedMovie = this.movies.get(selectedIndex);
                    new SelectShowtimeFrm(selectedMovie).setVisible(true);
                    this.dispose();
                } else if (currentList.equals("screenRooms")) {
                    ScreenRoom selectedScreenRoom = this.screenRooms.get(selectedIndex);
                    // Mở cửa sổ chọn suất chiếu cho phòng đã chọn
                    new SelectShowtimeFrm(selectedScreenRoom).setVisible(true);
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_displayListValueChanged

    private void listMoviesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listMoviesBtnActionPerformed
        currentList = "movies";
        lblTitle.setText("Movies");
        MovieDAO movieDAO = new MovieDAO();
        this.movies = movieDAO.listMovies();
        DefaultListModel<String> model = new DefaultListModel<>();
        for (Movie movie : this.movies) {
            model.addElement(movie.getTitle());
        }
        displayList.setModel(model);
    }//GEN-LAST:event_listMoviesBtnActionPerformed

    private void listScreenRoomsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listScreenRoomsBtnActionPerformed
        currentList = "screenRooms";
        lblTitle.setText("Screen Rooms");
        ScreenRoomDAO screenRoomDAO = new ScreenRoomDAO();
        this.screenRooms = screenRoomDAO.listScreenRooms();
        DefaultListModel<String> model = new DefaultListModel<>();
        for (ScreenRoom sr : this.screenRooms) {
            model.addElement(sr.getRoomCode() + " - " + sr.getCinema().getName());
        }
        displayList.setModel(model);
    }//GEN-LAST:event_listScreenRoomsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellTicketFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellTicketFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellTicketFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellTicketFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellTicketFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> displayList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton listMoviesBtn;
    private javax.swing.JButton listScreenRoomsBtn;
    // End of variables declaration//GEN-END:variables
}
